# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/qcom/common/system/av/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/qcom/common/system/av


PRODUCT_PACKAGES += \
    libmmparserextractor \
    libavenhancements \
    libmmosal \
    libmmparser_lite
